#Pathway enrichment analysis using tmod with Hallmark 

# Figure 3e
#Reference: https://d3amtssd1tejdt.cloudfront.net/2016/2420/1/tmod.pdf
#devtools::install_version("tmod", version = "0.40", repos = "http://cran.us.r-project.org")

## http://www.broadinstitute.org/gsea/downloads.jsp 
#download the  msigdb_v7.2.xml
#Hallmark gene sets summarize and represent specific well-defined biological states or processes and display coherent expression. These gene sets were generated by a computational methodology based on identifying overlaps between gene sets in other MSigDB collections and retaining genes that display coordinate expression.

library(tmod)
library(dplyr)
#read the files as follow
#The files are from Deseq2 output. They represent all All DEG after Shrinkage estimate without padj cuttof
FL_0h_vs_WT_0h <- read.csv("~/DEGs_All_LFShrinkage FL_0h _vs_ WT_0h .csv", sep=",")
FL_1h_vs_WT_1h <- read.csv("~/DEGs_All_LFShrinkage FL_1h _vs_ WT_1h .csv", sep=",")


#Read file that changes  mouse genes to human orthologs
Mous_hum <- read.table("~/MGI_to_HGNC_lookup.txt", sep="\t", header = T)


msig <- tmodImportMSigDB(
  file = "~/msigdb_v7.2.xml",
  format = "xml",
  organism = "Homo sapiens",
  fields = c("STANDARD_NAME", "CATEGORY_CODE", "SUB_CATEGORY_CODE",
             "EXTERNAL_DETAILS_URL") )

#We want to limit our analysis only to the 50 “hallmark”module categories

sel <-msig$MODULES$Category =="H" #H for hallmark 
table(msig$MODULES$Subcategory)
table(sel)
#change the gene names for all the files as follow

#order the genes 
FL_0h_vs_WT_0h_genes <- FL_0h_vs_WT_0h[order(FL_0h_vs_WT_0h$padj),]
FL_1h_vs_WT_1h_genes <- FL_1h_vs_WT_1h[order(FL_1h_vs_WT_1h$padj),]

#run the rest
res.FL_0h_vs_WT_0h_genes <- tmodCERNOtest(FL_0h_vs_WT_0h_genes$Human.HGNC, mset=msig[sel]) #
res.FL_1h_vs_WT_1h_genes <- tmodCERNOtest(FL_1h_vs_WT_1h_genes$Human.HGNC, mset= msig[sel])


tmodPanelPlot(list(FL_0h_vs_WT_0h=res.FL_0h_vs_WT_0h_genes,
                   FL_1h_vs_WT_1h=res.FL_1h_vs_WT_1h_genes,
                   FL_12h_vs_WT_12h=res.FL_12h_vs_WT_12h_genes,
                   WT_1h_vs_WT_0h=res.WT_1h_vs_WT_0h_genes,
                   WT_12h_vs_WT_0h=res.WT_12h_vs_WT_0h_genes,
                   WT_12h_vs_WT_1h=res.WT_12h_vs_WT_1h_genes,
                   Fl_12h_vs_Fl_0h=res.Fl_12h_vs_Fl_0h_genes,
                   Fl_12h_vs_Fl_1h=res.Fl_12h_vs_Fl_1h_genes),
              filter.rows.auc = 0.5,
              pie=pies, pie.style = "rug", grid="b", pval.thr = 10^-2, pval.thr.lower = 10^-6, 
              text.cex=1.2, filter.by.id = c("M5890", "M5902", "M5932" ,"M5896", "M5891", "M5897" ,"M5939" ,"M5941" ,"M5947" ,"M5930" ,"M5936",
                                             "M5942" ,"M5953" ,"M5924" ,"M5950" ,"M5906" ,"M5934" ,"M5898" ,"M5901" ,"M5907" ,"M5926",
                                             "M5913" ,"M5925"  ,"M5915" ,"M5946" ,"M5911" ,"M5921" ,"M5892" ,"M5903" ,"M5895"  ,"M5922"  ,"M5893" ,"M5916" ,"M5923" ,"M5944",
                                             "M5948" ,"M5908" ))